export const PROJECTS_DATA = [
  {
    id: 1,
    title: "Wanderlust – Travel Booking Platform",
    category: "Full Stack Web Application",
    shortDescription: "A full-stack travel accommodation platform inspired by Airbnb.",
    description: "A full-stack travel accommodation platform inspired by Airbnb that allows users to discover, create, edit, and manage travel listings. Users can securely authenticate, upload listing images, and interact with the platform through a responsive and intuitive interface.",
    problemStatement: null,
    solution: null,
    features: [
      "Secure user authentication",
      "Create, edit, and delete listings",
      "Image uploads with Cloudinary",
      "Reviews and ratings",
      "Responsive UI",
      "RESTful API architecture",
    ],
    techStack: ["Node.js", "Express.js", "MongoDB", "Mongoose", "EJS", "Passport.js", "Cloudinary", "Bootstrap"],
    challenges: null,
    learnings: null,
    githubLink: "#",
    image: "../public/images/wanderlust.png", 
  },
  {
    id: 2,
    title: "Data Download Duplication Alert System",
    category: "Desktop Automation Application",
    shortDescription: "Intelligent desktop utility that detects and prevents duplicate file downloads in real-time.",
    description: "An intelligent desktop utility that monitors downloaded files in real time, detects duplicate downloads using cryptographic hashing, and automatically alerts users before redundant storage is consumed.",
    problemStatement: null,
    solution: null,
    features: [
      "Real-time download monitoring",
      "SHA-256 duplicate detection",
      "Automatic duplicate alerts",
      "SQLite database integration",
      "Notification system",
      "Efficient file management",
    ],
    techStack: ["Python", "Watchdog", "SQLite", "Tkinter", "Hashlib", "Plyer"],
    challenges: null,
    learnings: null,
    githubLink: "",
    image: "../public/images/ddas.png", 
  },
  {
    id: 3,
    title: "Crop Recommendation System",
    category: "Machine Learning Application",
    shortDescription: "ML-based system predicting the most suitable crop using soil and environmental data.",
    description: "A machine learning-based crop recommendation system that predicts the most suitable crop using soil nutrients and environmental parameters, helping farmers make informed agricultural decisions.",
    problemStatement: null,
    solution: null,
    features: [
      "Crop prediction using ML models",
      "Data preprocessing and feature engineering",
      "Model evaluation",
      "High prediction accuracy",
      "Interactive prediction interface",
      "Real-world agricultural dataset",
    ],
    techStack: ["Python", "Scikit-learn", "Pandas", "NumPy", "Matplotlib", "Flask"],
    challenges: null,
    learnings: null,
    githubLink: "https://github.com/chunchun-06/cropalyst.git",
    image: "../public/images/crop.png", 
  },
  {
    id: 4,
    title: "Internship Matchmaking System",
    category: "Full Stack Web Application",
    shortDescription: "A smart recommendation platform connecting students with relevant internships.",
    description: "A smart internship recommendation platform that connects students with relevant internship opportunities based on their skills, interests, and academic profile while helping recruiters discover suitable candidates.",
    problemStatement: null,
    solution: null,
    features: [
      "Student authentication",
      "Recruiter dashboard",
      "Skill-based internship matching",
      "Profile management",
      "Internship listings",
      "Search and filtering",
    ],
    techStack: ["java","sqlite"],
    challenges: null,
    learnings: null,
    githubLink: "https://github.com/chunchun-06/Internship_Matching_Engine.git",
    image: "../public/images/intern.png",
  }
];
